-- vim.api.nvim_create_autocmd({ "BufWinEnter" }, {
--   group = vim.api.nvim_create_augroup("cmp", { clear = true }),
--   pattern = "*",
--   callback = function()
--     require('cmp').setup.buffer({ sources = {{ name = 'vim-dadbod-completion' }} })
--   end,
-- })
