require("config.remap")
require("config.packer")
require("config.mason")
require("config.eslint")
require("config.lsp")
require("config.set")
require("config.hardtime")
require("config.abbrs")
require("config.lualine")
require("config.oil")

require 'hex'.setup()
